package dbadmin.backend.ddl;

import java.util.List;
import java.util.regex.Pattern;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Component;

/**
 * Tablo/Kolon metadata'sinin arkasinda gercek {@code CREATE/ALTER/DROP TABLE} SQL'ini
 * calistiran sinif — burasi metadata katmanini gercek Postgres semasiyla senkron tutan yer.
 * <p>
 * Onemli detay: JDBC'nin {@code ?} placeholder'lari sadece deger icin calisir, tablo/kolon
 * ismi gibi identifier'lar icin calismaz. O yuzden burada SQL string olarak elle birlestiriliyor
 * ({@code "CREATE TABLE " + tableName + ...}); bu normalde SQL injection riski olurdu, ama
 * {@link #quote} her identifier'i ayni whitelist regex'inden gecirip cift tirnak icine aliyor
 * ({@code "isim"}), boylece guvenli hale geliyor.
 */
@Component
public class TableDdlExecutor {

    /** {@link dbadmin.backend.validation.NameValidator} ile ayni kural: SQL'e gitmeden son bir savunma katmani. */
    private static final Pattern IDENTIFIER_PATTERN = Pattern.compile("^[a-z0-9_][A-Za-z0-9_]{1,29}$");

    private final JdbcTemplate jdbcTemplate;

    public TableDdlExecutor(JdbcTemplate jdbcTemplate) {
        this.jdbcTemplate = jdbcTemplate;
    }

    /** createTable'a verilecek tek bir kolon tanimi: isim + tip. Ayri bir class degil, kucuk bir veri tasiyici (record). */
    public record ColumnDefinition(String name, ColumnType type) {
    }

    /** Kullanicinin kolon listesinde hic yer almayan, her tabloya sabit eklenen primary key kolonu. */
    private static final String ID_COLUMN_SQL = "\"id\" int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";

    /** Gercek {@code CREATE TABLE "schema"."isim" ("id" ..., "kolon1" tip1, ...)} calistirir; id kolonu her zaman otomatik eklenir. */
    public void createTable(String schemaName, String tableName, List<ColumnDefinition> columns) {
        String columnsSql = columns.stream()
                .map(c -> quote(c.name()) + " " + c.type().postgresType())
                .reduce((a, b) -> a + ", " + b)
                .orElseThrow(() -> new IllegalArgumentException("a table needs at least one column"));
        jdbcTemplate.execute(
                "CREATE TABLE " + qualifiedName(schemaName, tableName) + " (" + ID_COLUMN_SQL + ", " + columnsSql + ")");
    }

    /** Tablo bir schema'dan digerine tasinmaz, sadece adi degisir — bu yuzden tek bir schemaName yeterli. */
    public void renameTable(String schemaName, String oldName, String newName) {
        jdbcTemplate.execute(
                "ALTER TABLE " + qualifiedName(schemaName, oldName) + " RENAME TO " + quote(newName));
    }

    /** Tablo silinince altindaki tum kolonlar da (gercek DB'de) otomatik gider — Postgres'in kendi davranisi. */
    public void dropTable(String schemaName, String tableName) {
        jdbcTemplate.execute("DROP TABLE " + qualifiedName(schemaName, tableName));
    }

    public void addColumn(String schemaName, String tableName, String columnName, ColumnType type) {
        jdbcTemplate.execute("ALTER TABLE " + qualifiedName(schemaName, tableName) + " ADD COLUMN "
                + quote(columnName) + " " + type.postgresType());
    }

    public void dropColumn(String schemaName, String tableName, String columnName) {
        jdbcTemplate.execute(
                "ALTER TABLE " + qualifiedName(schemaName, tableName) + " DROP COLUMN " + quote(columnName));
    }

    public void renameColumn(String schemaName, String tableName, String oldColumnName, String newColumnName) {
        jdbcTemplate.execute("ALTER TABLE " + qualifiedName(schemaName, tableName) + " RENAME COLUMN "
                + quote(oldColumnName) + " TO " + quote(newColumnName));
    }

    /** Tabloyu bir schema'dan digerine tasir; {@code currentSchemaName} tablonun su anki (eski) schema'sidir. */
    public void moveTableToSchema(String currentSchemaName, String tableName, String newSchemaName) {
        jdbcTemplate.execute(
                "ALTER TABLE " + qualifiedName(currentSchemaName, tableName) + " SET SCHEMA " + quote(newSchemaName));
    }

    /**
     * "public" disindaki schema'lardaki tablolar Postgres'in varsayilan {@code search_path}'inde
     * yer almaz — o yuzden her DDL'de tabloyu {@code "schema"."tablo"} seklinde tam nitelikli
     * (fully qualified) yaziyoruz; sadece tablo adini yazmak "public" disinda bir schema'daki
     * tabloyu bulamaz.
     */
    private String qualifiedName(String schemaName, String tableName) {
        return quote(schemaName) + "." + quote(tableName);
    }

    /**
     * Bir identifier'i (schema/tablo/kolon adi) SQL'e gomulmeden once dogrular ve cift tirnaga alir.
     * Buraya gelen isim zaten {@link dbadmin.backend.validation.NameValidator}'dan gecmis olmali;
     * bu ikinci kontrol son bir guvenlik agi (defense in depth) — kullaniciya gosterilen bir
     * validasyon hatasi degil, "buraya kadar gelmemesi gereken bir sey geldi" anlaminda
     * {@link IllegalStateException} firlatir.
     */
    private String quote(String identifier) {
        if (identifier == null || !IDENTIFIER_PATTERN.matcher(identifier).matches()) {
            throw new IllegalStateException("unsafe identifier reached the DDL layer: " + identifier);
        }
        return "\"" + identifier + "\"";
    }
}
